apiVersion: apps/v1
kind: Deployment
metadata:
  name: testccc
  labels:
    app: testccc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testccc
  template:
    metadata:
      labels:
        app: testccc
    spec:
      containers:
        - name: testccc
          image: dev.pineone.com:20444/action_test/test_ccc:latest
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: testccc
